python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_11
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_12
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_13
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_14
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_15
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_16
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_17
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_18
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_19
python main_collect_five_baseline.py --num_of_workers 12 --version 3 --map CollectMineralShardsFiveExtendedVersion2 --max_steps 3005000 --gpu 0 --postfix _collect_five_sparse_baseline_20
