python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_1
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_2
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_3
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_4
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_5
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_6
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_7
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_8
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_9
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 0 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.9999_10
