python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_1
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_2
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_3
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_4
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_5
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_6
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_7
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_8
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_9
python main_collect_five_nj.py --num_of_workers 11 --version 4 --gpu 1 --max_steps 2005000 --map CollectMineralShardsFiveExtendedVersion2 --postfix _dropout_all_transfer_no_scale_0.3_10
