# python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_11
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_12
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_13
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_14
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_15
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_16
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_17
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_18
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_19
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 1 --version 6 --transfer 0 --clipping False --annealing False --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_wo_clipping_20
