python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_1
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_2
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_3
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_4
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_5
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_6
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_7
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_8
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_9
python main_nj_collect_and_destroy.py --map CollectAndDestroyAirSCV --gpu 1 --num_of_workers 6 --version 1 --clip_grad 3.0 --learning_rate 1e-5 --max_steps 2505000 --postfix _collect_and_destroy_air_scv_no_bn_annealing_0.0001_clipgrad3.0_10

