python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_1
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_2
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_3
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_4
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_5
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_6
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_7
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_8
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_9
python main_nj_collect_and_destroy.py --max_steps 2505000 --learning_rate 1e-5 --num_of_workers 7 --gpu 0 --version 6 --transfer 0 --postfix _collect_and_destroy_new_lr_1e-5_wo_bn_wo_annealing_10
